#!/usr/bin/env bash
#
# dev-instance.sh — spin up a throwaway, *populated* Stash instance that an
# agent can drive (chrome-devtools, GraphQL) to verify changes for real.
#
# It boots a backend on a free port against a fresh SQLite DB (auto-created +
# migrated to the current appSchemaVersion), then seeds it with performers /
# studios / tags over the live GraphQL API (see dev-seed.py). No setup wizard:
# writing a config.yml makes IsNewSystem() false, so it boots straight into a
# usable, populated UI.
#
# Commands:
#   up [--ui] [--scenario NAME] [--seed-args "..."]
#                                   ensure ONE instance is up (build/boot/seed if
#                                   needed, else reuse) and print its URL on stdout.
#                                   --ui also (re)starts the vite hot-reload UI.
#                                   idempotent — callers never pick or track ports.
#                                   scenarios: default|minimal|empty|multi-image|edge
#   down                            stop processes, remove the instance dir
#   restart [...]                   rebuild backend + reboot, RE-SEED fresh (same flags as up)
#   status                          show whether it's up and where
#   logs [-f]                       print (or follow) the backend log
#   url                             print the URL to hit (UI if running, else backend)
#   gql '<query>' ['<vars-json>']   POST a GraphQL query to the running instance
#
# State lives in $REPO/.dev (gitignored). One instance at a time, on purpose:
# tools that follow (verify-ui, gql) just read .dev/instance.env.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEV="$REPO/.dev"
ENVF="$DEV/instance.env"
BIN="$DEV/stash-bin"
DB="$DEV/stash.sqlite"
CONF="$DEV/config.yml"
LOG="$DEV/stash.log"
UILOG="$DEV/ui.log"

c_grn=$'\e[32m'; c_dim=$'\e[2m'; c_red=$'\e[31m'; c_rst=$'\e[0m'
say()  { printf '%s\n' "$*" >&2; }
ok()   { printf '%s%s%s\n' "$c_grn" "$*" "$c_rst" >&2; }
die()  { printf '%s%s%s\n' "$c_red" "$*" "$c_rst" >&2; exit 1; }

gen_key() { openssl rand -hex 32 2>/dev/null || head -c32 /dev/urandom | xxd -p | tr -d '\n'; }

free_port() {
  local p
  for p in $(seq 9920 9999); do
    if ! { exec 3<>"/dev/tcp/127.0.0.1/$p"; } 2>/dev/null; then echo "$p"; return 0; fi
    exec 3>&- || true
  done
  die "no free port in 9920-9999"
}

load_env() { [ -f "$ENVF" ] && . "$ENVF" || return 1; }

is_running() {
  load_env 2>/dev/null || return 1
  [ -n "${BACKEND_PID:-}" ] && kill -0 "$BACKEND_PID" 2>/dev/null
}

build_backend() {
  say "${c_dim}building stash binary (make stash)...${c_rst}"
  # Same recipe as a normal dev build; embeds the existing ui/v2.5/build.
  make -C "$REPO" stash OUTPUT="$BIN" >&2 || die "backend build failed (see output above)"
}

write_config() {
  local port="$1"
  cat >"$CONF" <<YAML
# Generated by scripts/dev-instance.sh — throwaway dev instance. Do not commit.
stash: []
database: $DB
generated: $DEV/generated
cache: $DEV/cache
blobs_storage: DATABASE
host: 0.0.0.0
port: $port
jwt_secret_key: $(gen_key)
session_store_key: $(gen_key)
YAML
}

wait_healthz() {
  local port="$1" i
  for i in $(seq 1 80); do
    curl -fsS "http://localhost:$port/healthz" >/dev/null 2>&1 && return 0
    is_running || die "backend exited during startup — see: $0 logs"
    sleep 0.5
  done
  die "backend did not become healthy within 40s — see: $0 logs"
}

# Start the vite hot-reload UI against the running backend, recording UI_* in the
# env file. Idempotent: a live UI is left running. Call load_env first.
start_ui() {
  if [ -n "${UI_PID:-}" ] && kill -0 "$UI_PID" 2>/dev/null; then return 0; fi
  local uiport; uiport="$(free_port)"
  say "${c_dim}starting vite UI on :$uiport (hot reload)...${c_rst}"
  # invoke vite directly (not `pnpm run start --`, whose `--` leaks through and
  # makes vite ignore --port, binding its config default :3000 instead).
  # Trailing `</dev/null >/dev/null 2>&1` detaches the subshell's stdio from the
  # caller's — otherwise the backgrounded vite inherits and holds the caller's
  # stdout open, so `URL=$(… up --ui)` or `… up --ui | …` hangs forever on EOF.
  ( cd "$REPO/ui/v2.5" && VITE_APP_PLATFORM_URL="$STASH_URL" setsid pnpm exec vite --port "$uiport" --host --strictPort >"$UILOG" 2>&1 & echo $! >"$DEV/ui.pid" ) </dev/null >/dev/null 2>&1
  UI_PID="$(cat "$DEV/ui.pid")"; UI_PORT="$uiport"; UI_URL="http://localhost:$uiport"
  grep -v '^UI_' "$ENVF" >"$ENVF.tmp" 2>/dev/null || true; mv "$ENVF.tmp" "$ENVF"
  { echo "UI_PID=$UI_PID"; echo "UI_PORT=$UI_PORT"; echo "UI_URL=$UI_URL"; } >>"$ENVF"
}

# The one URL a caller should hit: the hot-reload UI if running, else the backend.
primary_url() { echo "${UI_URL:-$STASH_URL}"; }

cmd_up() {
  local with_ui=0 seed_args=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --ui) with_ui=1 ;;
      --scenario) seed_args="$seed_args --scenario $2"; shift ;;
      --seed-args) seed_args="$seed_args $2"; shift ;;
      *) die "unknown flag: $1" ;;
    esac
    shift
  done

  if is_running; then
    load_env
    [ "$with_ui" -eq 1 ] && start_ui   # honor --ui even on an already-running instance
    ok "already up — reusing → $(primary_url)"
    primary_url                         # stdout: just the URL, for callers
    return 0
  fi

  rm -rf "$DEV"
  mkdir -p "$DEV/generated" "$DEV/cache"

  build_backend
  local port; port="$(free_port)"
  write_config "$port"

  say "${c_dim}booting backend on :$port (fresh DB, auto-migrated)...${c_rst}"
  STASH_CONFIG_FILE="$CONF" setsid "$BIN" >"$LOG" 2>&1 &
  local pid=$!
  local url="http://localhost:$port"
  cat >"$ENVF" <<ENV
BACKEND_PID=$pid
BACKEND_PORT=$port
STASH_URL=$url
ENV
  wait_healthz "$port"

  say "${c_dim}seeding via GraphQL...${c_rst}"
  # shellcheck disable=SC2086
  python3 "$REPO/scripts/dev-seed.py" --url "$url" $seed_args >&2 \
    || die "seeding failed (instance still up at $url; see error above)"

  load_env   # re-read so start_ui / primary_url see STASH_URL from the env file
  if [ "$with_ui" -eq 1 ]; then
    start_ui
    ok "UP — built UI: $STASH_URL   |   vite (hot reload): $UI_URL"
  else
    ok "UP — $STASH_URL   (playground: $STASH_URL/playground)"
  fi
  primary_url   # stdout: the URL a caller should hit
}

cmd_down() {
  if load_env 2>/dev/null; then
    for pidvar in BACKEND_PID UI_PID; do
      local pid="${!pidvar:-}"
      [ -n "$pid" ] && kill -TERM -- "-$pid" 2>/dev/null || true
    done
  fi
  rm -rf "$DEV"
  ok "down — instance removed"
}

cmd_restart() { cmd_down; cmd_up "$@"; }

cmd_status() {
  if is_running; then
    load_env
    ok "up → $STASH_URL${UI_URL:+   ui: $UI_URL}"
    say "${c_dim}db: $DB   log: $LOG${c_rst}"
  else
    say "down"
  fi
}

cmd_logs() {
  [ -f "$LOG" ] || die "no log — instance not up?"
  if [ "${1:-}" = "-f" ]; then tail -f "$LOG"; else cat "$LOG"; fi
}

cmd_url() { load_env 2>/dev/null && primary_url || die "not up (run: $0 up)"; }

cmd_gql() {
  load_env 2>/dev/null || die "not up"
  local q="${1:?usage: gql '<query>' ['<vars-json>']}" vars="${2:-{}}"
  python3 - "$STASH_URL" "$q" "$vars" <<'PY'
import json, sys, urllib.request
url, q, vars = sys.argv[1], sys.argv[2], sys.argv[3]
req = urllib.request.Request(url.rstrip('/')+'/graphql',
    data=json.dumps({'query': q, 'variables': json.loads(vars)}).encode(),
    headers={'Content-Type': 'application/json'})
print(json.dumps(json.load(urllib.request.urlopen(req, timeout=30)), indent=2))
PY
}

cmd="${1:-}"; shift || true
case "$cmd" in
  up)      cmd_up "$@" ;;
  down)    cmd_down ;;
  restart) cmd_restart "$@" ;;
  status)  cmd_status ;;
  logs)    cmd_logs "$@" ;;
  url)     cmd_url ;;
  gql)     cmd_gql "$@" ;;
  *) say "usage: $0 {up [--ui] [--scenario NAME] [--seed-args \"...\"]|down|restart|status|logs [-f]|url|gql <q> [vars]}"; exit 2 ;;
esac
