// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// ClipReaderWriter is an autogenerated mock type for the ClipReaderWriter type
type ClipReaderWriter struct {
	mock.Mock
}

// AddO provides a mock function with given fields: ctx, id, dates
func (_m *ClipReaderWriter) AddO(ctx context.Context, id int, dates []time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, id, dates)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) []time.Time); ok {
		r0 = rf(ctx, id, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []time.Time) error); ok {
		r1 = rf(ctx, id, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddViews provides a mock function with given fields: ctx, sceneID, dates
func (_m *ClipReaderWriter) AddViews(ctx context.Context, sceneID int, dates []time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, sceneID, dates)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) []time.Time); ok {
		r0 = rf(ctx, sceneID, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []time.Time) error); ok {
		r1 = rf(ctx, sceneID, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// All provides a mock function with given fields: ctx
func (_m *ClipReaderWriter) All(ctx context.Context) ([]*models.Clip, error) {
	ret := _m.Called(ctx)

	var r0 []*models.Clip
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Clip); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Clip)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Count provides a mock function with given fields: ctx
func (_m *ClipReaderWriter) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountAllViews provides a mock function with given fields: ctx
func (_m *ClipReaderWriter) CountAllViews(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountUniqueViews provides a mock function with given fields: ctx
func (_m *ClipReaderWriter) CountUniqueViews(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountViews provides a mock function with given fields: ctx, id
func (_m *ClipReaderWriter) CountViews(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, newClip
func (_m *ClipReaderWriter) Create(ctx context.Context, newClip *models.Clip) error {
	ret := _m.Called(ctx, newClip)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Clip) error); ok {
		r0 = rf(ctx, newClip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAllViews provides a mock function with given fields: ctx, id
func (_m *ClipReaderWriter) DeleteAllViews(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteO provides a mock function with given fields: ctx, id, dates
func (_m *ClipReaderWriter) DeleteO(ctx context.Context, id int, dates []time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, id, dates)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) []time.Time); ok {
		r0 = rf(ctx, id, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []time.Time) error); ok {
		r1 = rf(ctx, id, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteViews provides a mock function with given fields: ctx, id, dates
func (_m *ClipReaderWriter) DeleteViews(ctx context.Context, id int, dates []time.Time) ([]time.Time, error) {
	ret := _m.Called(ctx, id, dates)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int, []time.Time) []time.Time); ok {
		r0 = rf(ctx, id, dates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, []time.Time) error); ok {
		r1 = rf(ctx, id, dates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Destroy provides a mock function with given fields: ctx, id
func (_m *ClipReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *ClipReaderWriter) Find(ctx context.Context, id int) (*models.Clip, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Clip
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Clip); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Clip)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindBySceneID provides a mock function with given fields: ctx, sceneID
func (_m *ClipReaderWriter) FindBySceneID(ctx context.Context, sceneID int) ([]*models.Clip, error) {
	ret := _m.Called(ctx, sceneID)

	var r0 []*models.Clip
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.Clip); ok {
		r0 = rf(ctx, sceneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Clip)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, sceneID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMany provides a mock function with given fields: ctx, ids
func (_m *ClipReaderWriter) FindMany(ctx context.Context, ids []int) ([]*models.Clip, error) {
	ret := _m.Called(ctx, ids)

	var r0 []*models.Clip
	if rf, ok := ret.Get(0).(func(context.Context, []int) []*models.Clip); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Clip)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllOCount provides a mock function with given fields: ctx
func (_m *ClipReaderWriter) GetAllOCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyLastViewed provides a mock function with given fields: ctx, ids
func (_m *ClipReaderWriter) GetManyLastViewed(ctx context.Context, ids []int) ([]*time.Time, error) {
	ret := _m.Called(ctx, ids)

	var r0 []*time.Time
	if rf, ok := ret.Get(0).(func(context.Context, []int) []*time.Time); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyOCount provides a mock function with given fields: ctx, ids
func (_m *ClipReaderWriter) GetManyOCount(ctx context.Context, ids []int) ([]int, error) {
	ret := _m.Called(ctx, ids)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, []int) []int); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyODates provides a mock function with given fields: ctx, ids
func (_m *ClipReaderWriter) GetManyODates(ctx context.Context, ids []int) ([][]time.Time, error) {
	ret := _m.Called(ctx, ids)

	var r0 [][]time.Time
	if rf, ok := ret.Get(0).(func(context.Context, []int) [][]time.Time); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyViewCount provides a mock function with given fields: ctx, ids
func (_m *ClipReaderWriter) GetManyViewCount(ctx context.Context, ids []int) ([]int, error) {
	ret := _m.Called(ctx, ids)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, []int) []int); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetManyViewDates provides a mock function with given fields: ctx, ids
func (_m *ClipReaderWriter) GetManyViewDates(ctx context.Context, ids []int) ([][]time.Time, error) {
	ret := _m.Called(ctx, ids)

	var r0 [][]time.Time
	if rf, ok := ret.Get(0).(func(context.Context, []int) [][]time.Time); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOCount provides a mock function with given fields: ctx, id
func (_m *ClipReaderWriter) GetOCount(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetODates provides a mock function with given fields: ctx, relatedID
func (_m *ClipReaderWriter) GetODates(ctx context.Context, relatedID int) ([]time.Time, error) {
	ret := _m.Called(ctx, relatedID)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int) []time.Time); ok {
		r0 = rf(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPerformerIDs provides a mock function with given fields: ctx, relatedID
func (_m *ClipReaderWriter) GetPerformerIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _m.Called(ctx, relatedID)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = rf(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTagIDs provides a mock function with given fields: ctx, relatedID
func (_m *ClipReaderWriter) GetTagIDs(ctx context.Context, relatedID int) ([]int, error) {
	ret := _m.Called(ctx, relatedID)

	var r0 []int
	if rf, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = rf(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetViewDates provides a mock function with given fields: ctx, relatedID
func (_m *ClipReaderWriter) GetViewDates(ctx context.Context, relatedID int) ([]time.Time, error) {
	ret := _m.Called(ctx, relatedID)

	var r0 []time.Time
	if rf, ok := ret.Get(0).(func(context.Context, int) []time.Time); ok {
		r0 = rf(ctx, relatedID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]time.Time)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, relatedID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: ctx, clipFilter, findFilter
func (_m *ClipReaderWriter) Query(ctx context.Context, clipFilter *models.ClipFilterType, findFilter *models.FindFilterType) ([]*models.Clip, int, error) {
	ret := _m.Called(ctx, clipFilter, findFilter)

	var r0 []*models.Clip
	if rf, ok := ret.Get(0).(func(context.Context, *models.ClipFilterType, *models.FindFilterType) []*models.Clip); ok {
		r0 = rf(ctx, clipFilter, findFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Clip)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, *models.ClipFilterType, *models.FindFilterType) int); ok {
		r1 = rf(ctx, clipFilter, findFilter)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *models.ClipFilterType, *models.FindFilterType) error); ok {
		r2 = rf(ctx, clipFilter, findFilter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// QueryCount provides a mock function with given fields: ctx, clipFilter, findFilter
func (_m *ClipReaderWriter) QueryCount(ctx context.Context, clipFilter *models.ClipFilterType, findFilter *models.FindFilterType) (int, error) {
	ret := _m.Called(ctx, clipFilter, findFilter)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, *models.ClipFilterType, *models.FindFilterType) int); ok {
		r0 = rf(ctx, clipFilter, findFilter)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.ClipFilterType, *models.FindFilterType) error); ok {
		r1 = rf(ctx, clipFilter, findFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetActivity provides a mock function with given fields: ctx, clipID, resetResume, resetDuration
func (_m *ClipReaderWriter) ResetActivity(ctx context.Context, clipID int, resetResume bool, resetDuration bool) (bool, error) {
	ret := _m.Called(ctx, clipID, resetResume, resetDuration)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int, bool, bool) bool); ok {
		r0 = rf(ctx, clipID, resetResume, resetDuration)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, bool, bool) error); ok {
		r1 = rf(ctx, clipID, resetResume, resetDuration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetO provides a mock function with given fields: ctx, id
func (_m *ClipReaderWriter) ResetO(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveActivity provides a mock function with given fields: ctx, clipID, resumeTime, playDuration
func (_m *ClipReaderWriter) SaveActivity(ctx context.Context, clipID int, resumeTime *float64, playDuration *float64) (bool, error) {
	ret := _m.Called(ctx, clipID, resumeTime, playDuration)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, int, *float64, *float64) bool); ok {
		r0 = rf(ctx, clipID, resumeTime, playDuration)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, *float64, *float64) error); ok {
		r1 = rf(ctx, clipID, resumeTime, playDuration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, updatedClip
func (_m *ClipReaderWriter) Update(ctx context.Context, updatedClip *models.Clip) error {
	ret := _m.Called(ctx, updatedClip)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Clip) error); ok {
		r0 = rf(ctx, updatedClip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePartial provides a mock function with given fields: ctx, id, partial
func (_m *ClipReaderWriter) UpdatePartial(ctx context.Context, id int, partial models.ClipPartial) (*models.Clip, error) {
	ret := _m.Called(ctx, id, partial)

	var r0 *models.Clip
	if rf, ok := ret.Get(0).(func(context.Context, int, models.ClipPartial) *models.Clip); ok {
		r0 = rf(ctx, id, partial)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Clip)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, models.ClipPartial) error); ok {
		r1 = rf(ctx, id, partial)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
